/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import entity.KhachHang;
import Repositories.KhachHangRP;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc acer
 */
public class KhachHangForm extends javax.swing.JPanel {

    DefaultTableModel tblModel;

    /**
     * Creates new form KhachHangForm
     */
    public KhachHangForm() {
        initComponents();
        initTB();
        loadTB();
    }

    public void initTB() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Khách Hàng", "Họ Tên", "Giới tính", "Email", "Điện Thoại", "Địa chỉ"});
        tblKH.setModel(tblModel);
    }

    public void loadTB() {
        try {
            KhachHangRP khRP = new KhachHangRP();
            List<KhachHang> list = khRP.loadTB();
            tblModel.setRowCount(0);
            for (KhachHang kh : list) {
                tblModel.addRow(new Object[]{
                    kh.getMaKH(), kh.getTenKH(), kh.getGioiTinh(), kh.getEmail(), kh.getDienThoai(), kh.getDiaChi()
                });
            }
            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKH = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lý Khách Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(768, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        txtTim.setBorder(null);
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        jPanel1.add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 231, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-24.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(22.0F);
        jSeparator1.setAlignmentY(22.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 231, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã Khách Hàng");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setText("Tên Khách Hàng");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Giới Tính");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel3.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 20));
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 20));
        jPanel3.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, 20));

        btnSua.setBackground(new java.awt.Color(110, 89, 222));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 30));

        btnXoa.setBackground(new java.awt.Color(110, 89, 222));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 30));

        btnThem.setBackground(new java.awt.Color(110, 89, 222));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 20));
        jPanel3.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, 20));

        jLabel8.setText("Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setText("Số Điện Thoại");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel10.setText("Địa Chỉ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        buttonGroup1.add(rbNam);
        rbNam.setText("Nam");
        jPanel3.add(rbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        buttonGroup1.add(rbNu);
        rbNu.setText("Nữ");
        jPanel3.add(rbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 390));

        btnTim.setBackground(new java.awt.Color(110, 89, 222));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        tblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Giới Tính", "Email", "Số Điện Thoại", "Địa chỉ"
            }
        ));
        tblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKH);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 700, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaKH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Mã Khách Hàng !!");
        } else if (txtTenKH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Tên Khách Hàng !!");
        }
        int chon = JOptionPane.showConfirmDialog(this, "Xác Nhận Sửa?", "Sửa?",
                JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            try {
                KhachHang sv = new KhachHang();
                sv.setMaKH(txtMaKH.getText());
                sv.setEmail(txtEmail.getText());
                sv.setDiaChi(txtDiachi.getText());
                sv.setTenKH(txtTenKH.getText());
                sv.setDienThoai(txtSdt.getText());
                sv.setGioiTinh(rbNam.isSelected() ? "Nam" : "Nữ");
                KhachHangRP dao = new KhachHangRP();
                if (dao.upDateKh(sv)) {
                    JOptionPane.showMessageDialog(this, "Thành Công");
                    loadTB();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi!!");

                }
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaKH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Mã Khách Hàng !!");
        } else if (txtTenKH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Tên Khách Hàng !!");
        }
        int chon = JOptionPane.showConfirmDialog(this, "Xóa?", "Xóa?",
                JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            try {
                KhachHangRP dao = new KhachHangRP();
                if (dao.deteleKH(txtMaKH.getText())) {
                    JOptionPane.showMessageDialog(this, "Thành Công");
                    loadTB();
                    txtDiachi.setText("");
                    txtEmail.setText("");
                    txtSdt.setText("");
                    txtMaKH.setText("");
                    txtTenKH.setText("");
                    txtEmail.setText("");
                    buttonGroup1.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi!!");

                }
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtTenKH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập Tên Khách Hàng !!");
        }
        int chon = JOptionPane.showConfirmDialog(this, "Xác Nhận thêm?", "Thêm?",
                JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            try {
                KhachHang sv = new KhachHang();
                sv.setMaKH(txtMaKH.getText());
                sv.setEmail(txtEmail.getText());
                sv.setDiaChi(txtDiachi.getText());
                sv.setTenKH(txtTenKH.getText());
                sv.setDienThoai(txtSdt.getText());
                sv.setGioiTinh(rbNam.isSelected() ? "Nam" : "Nữ");
                KhachHangRP dao = new KhachHangRP();
                if (dao.insertKH(sv)) {
                    JOptionPane.showMessageDialog(this, "Thành Công");
                    loadTB();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi!!");

                }
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if (txtTim.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã Khách Hàng !!");
        } else {
            try {
                KhachHangRP dao = new KhachHangRP();
                KhachHang bd = dao.searchMaKH(txtTim.getText());
                if (bd != null) {
                    txtDiachi.setText(bd.getDiaChi());
                    txtEmail.setText(bd.getEmail());
                    txtTenKH.setText(bd.getTenKH());
                    txtMaKH.setText(bd.getMaKH());
                    txtSdt.setText(bd.getDienThoai());
                    txtEmail.setText(bd.getEmail());
                    if (bd.getGioiTinh().equals("Nam")) {
                        rbNam.setSelected(true);
                    } else if (bd.getGioiTinh().equals("Nữ")) {
                        rbNu.setSelected(true);
                    } else {
                        buttonGroup1.clearSelection();
                    }
                    JOptionPane.showMessageDialog(this, "Đã tìm thấy!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Mã Khách Hàng không tồn tại!!");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKHMouseClicked
        try {
            int row = tblKH.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblKH.getValueAt(row, 0);
                KhachHangRP dao = new KhachHangRP();
                KhachHang sv = dao.searchMaKH(id);
                if (sv != null) {
                    txtTenKH.setText(sv.getTenKH());
                    txtEmail.setText(sv.getEmail());
                    txtMaKH.setText(sv.getMaKH());
                    txtSdt.setText(sv.getDienThoai());
                    txtDiachi.setText(sv.getDiaChi());
                    if (sv.getGioiTinh().equals("Nam")) {
                        rbNam.setSelected(true);
                    } else if (sv.getGioiTinh().equals("Nữ")) {
                        rbNu.setSelected(true);
                    } else {
                        buttonGroup1.clearSelection();
                    }

                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblKHMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tblKH;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
