CREATE DATABASE QLBH1
GO
USE QLBH1
GO
CREATE TABLE KHACHHANG(
MAKH CHAR(7) PRIMARY KEY,
TENKH NVARCHAR(25),
SODT NVARCHAR(10),
DIACHI NVARCHAR(25),
EMAIL NVARCHAR(20),
CCCD NVARCHAR(25),
TRANGTHAI NVARCHAR(15),
)
GO
CREATE TABLE CHUCVU(
MACV CHAR(7) PRIMARY KEY,
TENCV NVARCHAR(25),
HESOLUONG CHAR(5)
)

CREATE TABLE NHANVIEN(
MANV CHAR(7) PRIMARY KEY,
MACV CHAR(7) FOREIGN KEY REFERENCES CHUCVU(MACV),
TENNV NVARCHAR(25),
GIOITINH NVARCHAR(10),
NGAYSINH NVARCHAR(15),
EMAIL NVARCHAR(25),
DIENTHOAI CHAR(10),
CCCD NVARCHAR(15),
DIACHI NVARCHAR(25),
NGAYVAOLAM NVARCHAR(15),
)
GO
CREATE TABLE TAIKHOAN(
TENDN CHAR(15) PRIMARY KEY,
MATKHAU CHAR(10),
MANV CHAR(7) FOREIGN KEY REFERENCES NHANVIEN(MANV),
)
GO



CREATE TABLE LOAISP(
MALOAI CHAR(7) PRIMARY KEY,
TENLOAI NVARCHAR(25),
NGAYTAO NVARCHAR(15),



)
GO
CREATE TABLE CHATLIEU(
MACHATLIEU CHAR(7) PRIMARY KEY,
TENCHATLIEU NVARCHAR(25),
)
GO


CREATE TABLE MAUSAC(
MAMAUSAC CHAR(7) PRIMARY KEY,
TENMAUSAC NVARCHAR(25),
)
GO
CREATE TABLE SANPHAM(
MASP CHAR(7) PRIMARY KEY,
MALOAI CHAR(7) FOREIGN KEY REFERENCES LOAISP(MALOAI),
MACHATLIEU CHAR(7) FOREIGN KEY REFERENCES CHATLIEU(MACHATLIEU),
XUATXU NVARCHAR(25),
MAMAUSAC CHAR(7) FOREIGN KEY REFERENCES MAUSAC(MAMAUSAC), 
TENSANPHAM NVARCHAR(25),
SOLUONG INT,
GIABAN NVARCHAR(15),
TRONGLUONG INT,

)
GO
CREATE TABLE HOADONBANHANG(
MAHDBH CHAR(7) PRIMARY KEY,
MAKH CHAR(7) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
MANV CHAR(7),
NGAYLAPHD NVARCHAR(15),
TONGTIEN CHAR(15),
)
GO
CREATE TABLE CT_HOADONBANHANG(
MAHDBH CHAR(7) PRIMARY KEY FOREIGN KEY REFERENCES HOADONBANHANG(MAHDBH),
MASP CHAR(7) FOREIGN KEY REFERENCES SANPHAM(MASP),
SOLUONG INT,
DONGIA NVARCHAR(25),
)
GO
CREATE TABLE HOADONNHAPHANG(
MAHDNH CHAR(7) PRIMARY KEY,
MANHACC CHAR(7),
MANV CHAR(7) FOREIGN KEY REFERENCES NHANVIEN(MANV),
NGAYLAPHOADON NVARCHAR(25),
TONGTIEN NVARCHAR(20),
)
GO
CREATE TABLE CT_HOADONNHAPHANG(
MAHDNH CHAR(7) PRIMARY KEY FOREIGN KEY REFERENCES HOADONNHAPHANG(MAHDNH),
MASP CHAR(7)  FOREIGN KEY REFERENCES SANPHAM(MASP),
SOLUONG INT,
DONGIA NVARCHAR(25)

)
GO
CREATE TABLE NhaCungCap(
MaNhaCC CHAR(7) PRIMARY KEY,
TenNhaCC NVarChar(25),
soDT Char(10),
Email NVarChar(25),
DiaChi NvarChar(20)
)
