/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import entity.KhachHang;
import entity.NhaCungCap;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;

/**
 *
 * @author pc acer
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private NhaCungCapForm Ncc;
    private NhanVienForm Nv;
    private KhachHangForm kh;
    private ChatLieuForm chatLieu;
    private ChucVuForm Cv;
    private HDBHForm hdbh;
    private HDCTForm hdct;
    private HDNHForm hdnh;
    private SanPhamForm sp;
    private TaiKhoanForm tk;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        btn_TrangChu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_NhaCungCap = new javax.swing.JButton();
        btn_SanPham = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_TaiKhoan = new javax.swing.JButton();
        btn_ChucVu = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_ChatLieu = new javax.swing.JButton();
        btn_DoiMatKhau = new javax.swing.JButton();
        btn_NhanVien = new javax.swing.JButton();
        btn_HDNH = new javax.swing.JButton();
        btn_HDBH = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_HDCT = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        btn_chatLieu3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        TblPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cửa Hàng Bảo Hộ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btn_TrangChu.setBackground(new java.awt.Color(54, 33, 89));
        btn_TrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btn_TrangChu.setText("           Trang Chủ");
        btn_TrangChu.setBorder(null);
        btn_TrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(btn_TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 260, 40));

        jPanel4.setBackground(new java.awt.Color(54, 33, 89));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản Lý");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 30));

        btn_NhaCungCap.setBackground(new java.awt.Color(54, 33, 89));
        btn_NhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_NhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        btn_NhaCungCap.setText("                      Nhà Cung Cấp");
        btn_NhaCungCap.setBorder(null);
        btn_NhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhaCungCapActionPerformed(evt);
            }
        });
        jPanel3.add(btn_NhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 250, 20));

        btn_SanPham.setBackground(new java.awt.Color(54, 33, 89));
        btn_SanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_SanPham.setText("                      Sản Phẩm");
        btn_SanPham.setBorder(null);
        btn_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamActionPerformed(evt);
            }
        });
        jPanel3.add(btn_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 250, 20));

        btn_KhachHang.setBackground(new java.awt.Color(54, 33, 89));
        btn_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_KhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_KhachHang.setText("                      Khách Hàng");
        btn_KhachHang.setBorder(null);
        btn_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 220, 250, 20));

        btn_TaiKhoan.setBackground(new java.awt.Color(54, 33, 89));
        btn_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_TaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaiKhoan.setText("                      Tài Khoản");
        btn_TaiKhoan.setBorder(null);
        btn_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoanActionPerformed(evt);
            }
        });
        jPanel3.add(btn_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 250, 20));

        btn_ChucVu.setBackground(new java.awt.Color(54, 33, 89));
        btn_ChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ChucVu.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChucVu.setText("                      Chức Vụ");
        btn_ChucVu.setBorder(null);
        btn_ChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChucVuActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 250, 20));

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hóa Đơn");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 30));

        btn_ChatLieu.setBackground(new java.awt.Color(54, 33, 89));
        btn_ChatLieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ChatLieu.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChatLieu.setText("                      Chất Liệu");
        btn_ChatLieu.setBorder(null);
        btn_ChatLieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChatLieuActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ChatLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 250, 20));

        btn_DoiMatKhau.setBackground(new java.awt.Color(54, 33, 89));
        btn_DoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_DoiMatKhau.setText("                      Đổi Mật Khẩu");
        btn_DoiMatKhau.setBorder(null);
        btn_DoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMatKhauActionPerformed(evt);
            }
        });
        jPanel3.add(btn_DoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 250, 20));

        btn_NhanVien.setBackground(new java.awt.Color(54, 33, 89));
        btn_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btn_NhanVien.setText("                      Nhân Viên");
        btn_NhanVien.setBorder(null);
        btn_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVienActionPerformed(evt);
            }
        });
        jPanel3.add(btn_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 250, 20));

        btn_HDNH.setBackground(new java.awt.Color(54, 33, 89));
        btn_HDNH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_HDNH.setForeground(new java.awt.Color(255, 255, 255));
        btn_HDNH.setText("                      Hóa Đơn Nhập Hàng");
        btn_HDNH.setBorder(null);
        btn_HDNH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_HDNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HDNHActionPerformed(evt);
            }
        });
        jPanel3.add(btn_HDNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 350, 250, 20));

        btn_HDBH.setBackground(new java.awt.Color(54, 33, 89));
        btn_HDBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_HDBH.setForeground(new java.awt.Color(255, 255, 255));
        btn_HDBH.setText("                      Hóa Đơn Bán Hàng");
        btn_HDBH.setBorder(null);
        btn_HDBH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_HDBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HDBHActionPerformed(evt);
            }
        });
        jPanel3.add(btn_HDBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 370, 250, 20));

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tài Khoản");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        btn_HDCT.setBackground(new java.awt.Color(54, 33, 89));
        btn_HDCT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_HDCT.setForeground(new java.awt.Color(255, 255, 255));
        btn_HDCT.setText("                      Hóa Đơn Chi Tiết");
        btn_HDCT.setBorder(null);
        btn_HDCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_HDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HDCTActionPerformed(evt);
            }
        });
        jPanel3.add(btn_HDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 390, 250, 20));

        btn_DangXuat.setBackground(new java.awt.Color(54, 33, 89));
        btn_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_DangXuat.setText("                      Đăng Xuất");
        btn_DangXuat.setBorder(null);
        btn_DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });
        jPanel3.add(btn_DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 250, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 580));

        btn_chatLieu3.setBackground(new java.awt.Color(54, 33, 89));
        btn_chatLieu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_chatLieu3MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Chất Liệu");

        javax.swing.GroupLayout btn_chatLieu3Layout = new javax.swing.GroupLayout(btn_chatLieu3);
        btn_chatLieu3.setLayout(btn_chatLieu3Layout);
        btn_chatLieu3Layout.setHorizontalGroup(
            btn_chatLieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_chatLieu3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        btn_chatLieu3Layout.setVerticalGroup(
            btn_chatLieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_chatLieu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btn_chatLieu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 20));
        jPanel2.add(TblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 970, 580));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 580));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btn_chatLieu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chatLieu3MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_chatLieu3MousePressed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        // TODO add your handling code here:
         if ( kh == null) {
            kh = new KhachHangForm();
           
            TblPanel.addTab("Khách Hàng",kh);
        }
       TblPanel.setSelectedComponent(kh);
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoanActionPerformed
        // TODO add your handling code here:
         if ( tk == null) {
            tk = new TaiKhoanForm();
           
            TblPanel.addTab("Tài Khoản",tk);
        }
       TblPanel.setSelectedComponent(tk);
    }//GEN-LAST:event_btn_TaiKhoanActionPerformed

    private void btn_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChucVuActionPerformed
        // TODO add your handling code here:
         if ( Cv == null) {
            Cv = new ChucVuForm();
           
            TblPanel.addTab("Chức Vụ",Cv);
        }
       TblPanel.setSelectedComponent(Cv);
    }//GEN-LAST:event_btn_ChucVuActionPerformed

    private void btn_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DoiMatKhauActionPerformed

    private void btn_NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhaCungCapActionPerformed
        // TODO add your handling code here:
        if ( Ncc == null) {
            Ncc = new NhaCungCapForm();
           
            TblPanel.addTab("Nhà Cung Cấp",Ncc);
        }
       TblPanel.setSelectedComponent(Ncc);
    
    }//GEN-LAST:event_btn_NhaCungCapActionPerformed

    private void btn_ChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChatLieuActionPerformed
        // TODO add your handling code here:
         if ( chatLieu == null) {
            chatLieu = new ChatLieuForm();
           
            TblPanel.addTab("Chất Liệu",chatLieu);
        }
       TblPanel.setSelectedComponent(chatLieu);
    }//GEN-LAST:event_btn_ChatLieuActionPerformed

    private void btn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVienActionPerformed
        // TODO add your handling code here:
        if ( Nv == null) {
            Nv = new NhanVienForm();
           
            TblPanel.addTab("Nhân Viên",Nv);
        }
       TblPanel.setSelectedComponent(Nv);
      
        
    }//GEN-LAST:event_btn_NhanVienActionPerformed

    private void btn_HDNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HDNHActionPerformed
        // TODO add your handling code here:
        if ( hdnh == null) {
            hdnh = new HDNHForm();
           
            TblPanel.addTab("Hóa Đơn Nhập Hàng",hdnh);
        }
       TblPanel.setSelectedComponent(hdnh);
    }//GEN-LAST:event_btn_HDNHActionPerformed

    private void btn_HDBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HDBHActionPerformed
        // TODO add your handling code here:
        if ( hdbh == null) {
            hdbh = new HDBHForm();
           
            TblPanel.addTab("Hóa Đơn Bán Hàng",hdbh);
        }
       TblPanel.setSelectedComponent(hdbh);
    }//GEN-LAST:event_btn_HDBHActionPerformed

    private void btn_HDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HDCTActionPerformed
        // TODO add your handling code here:
        if ( hdct == null) {
            hdct = new HDCTForm();
           
            TblPanel.addTab("Hóa Đơn Chi Tiết",hdct);
        }
       TblPanel.setSelectedComponent(hdct);
    }//GEN-LAST:event_btn_HDCTActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamActionPerformed
        // TODO add your handling code here:
        if ( sp == null) {
            sp = new SanPhamForm();
           
            TblPanel.addTab("Sản Phẩm",sp);
        }
       TblPanel.setSelectedComponent(sp);
    }//GEN-LAST:event_btn_SanPhamActionPerformed
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));

    }
   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                new NhaCungCapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TblPanel;
    private javax.swing.JButton btn_ChatLieu;
    private javax.swing.JButton btn_ChucVu;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_DoiMatKhau;
    private javax.swing.JButton btn_HDBH;
    private javax.swing.JButton btn_HDCT;
    private javax.swing.JButton btn_HDNH;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_NhaCungCap;
    private javax.swing.JButton btn_NhanVien;
    private javax.swing.JButton btn_SanPham;
    private javax.swing.JButton btn_TaiKhoan;
    private javax.swing.JButton btn_TrangChu;
    private javax.swing.JPanel btn_chatLieu3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
